name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときにトリガー


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Amazon ECR にログイン
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Docker イメージをビルドして Amazon ECR にプッシュ
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: 669505788985.dkr.ecr.ap-northeast-1.amazonaws.com  # AWS アカウント ID とリージョン
          ECR_REPOSITORY: my-image  # ECR に作成したリポジトリ名
          IMAGE_TAG: latest  # イメージのタグ（例: latest）
        run: |
          # Docker イメージをビルド
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # イメージをリポジトリのフルパスにタグ付け
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # イメージを ECR にプッシュ
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
