name: Deploy to AWS

# トリガー条件
# このワークフローは、mainブランチにマージ(変更がプッシュ)されたときに実行されます。
on:
  push:
    branches:
      - main

# 環境変数の設定
env:
  AWS_REGION: ap-northeast-1
  

# ジョブの構成
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # AWS認証情報の設定
      # aws-actions/configure-aws-credentialsを使用して、GitHubのシークレットに保存したAWSアクセスキーとシークレットキーを用いて認証。
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # IAMユーザー情報の取得
      - name: Execute AWS CLI
        run: aws iam get-user
